### ISSUE TITLE
Snappy 1.1.8

### ISSUE THREAD

**Issue by Ingvar-Y** [conda-forge/python-snappy-feedstock#18]
Issue:
It seems `python-snappy` requires `snappy>=1.1.7,<1.1.8.0a0` according to conda solver:
```
UnsatisfiableError: The following specifications were found to be incompatible w
ith each other:



Package snappy conflicts for:
arrow-cpp==0.16.0=py37h750224e_1 -> snappy[version='>=1.1.8,<2.0a0']
parquet-cpp==1.5.1=2 -> arrow-cpp[version='>=0.11.0'] -> snappy[version='>=1.1.7
,<1.1.8.0a0|>=1.1.8,<2.0a0']
python-snappy==0.5.4=py37hd25c944_1 -> snappy[version='>=1.1.7,<1.1.8.0a0']
pyarrow==0.16.0=py37hecaa37c_2 -> arrow-cpp[version='>=0.16.0,<0.16.1.0a0'] -> s
nappy[version='>=1.1.8,<2.0a0']
pyarrow==0.16.0=py37hecaa37c_2 -> snappy
snappy==1.1.8=he025d50_1
```
This is weird since source repository states requirements are snappy library >= 1.0.2 (or revision 27) and it prevents using python-snappy with newer packages.

Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : base
    active env location : C:\Users\user\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.8.0
    conda-build version : not installed
         python version : 3.6.7.final.0
       virtual packages :
       base environment : C:\Users\user\AppData\Local\Continuum\miniconda3
 (writable)
           channel URLs : file:///channel/win-64
                          file:///channel/noarch
          package cache : C:\Users\user\AppData\Local\Continuum\miniconda3\
pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\AppData\Local\Continuum\miniconda3\
envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.0 requests/2.23.0 CPython/3.6.7 Windows/2008
ServerR2 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : True
```
</details>

Details may look unusual since I use a local channel with packages from conda-forge to update miniconda on a server without Internet access.

**Comment by martindurant** [comment]
From the output, it seems that the new release of arrow is the change that has made this appear now. I assume things would still work for arrow=0.15.x. 

You are welcome to propose a PR to this repo to update the requirement, but please do check that snappy (this python wrapper) does indeed still work.

**Comment by Ingvar-Y** [comment]
Managing pins through conda-forge is way over my head. I don't understand why it changed from 1.1.6|1.1.7 to 1.1.7 during Jinja2 migration and whether it is possible to pin to 1.1.7|1.1.8 or 1.1.8 only and how to do it. Maybe @xhochy would be kind enough to help?

**Comment by xhochy** [comment]
We should rebuild `python-snappy` as the pinning can be more wider. `python-snappy` should suppoer anything upto `2.0`. This is already fixed in `conda-forge-pinning` and will be applied through a rerender.
