### ISSUE TITLE
conda-forge packaging for python-snappy 0.6.0?

### ISSUE THREAD

**Issue by zaneselvans** [conda-forge/python-snappy-feedstock#26]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

### Issue:
Just wondering if there are plans to package python-snappy 0.6.0 on conda-forge, or if there's some reason what that's blocked from happening or undesirable. It's been out for ~2 months [on the default conda channel](https://anaconda.org/anaconda/python-snappy)

Thanks!

**Comment by martindurant** [comment]
Done: https://github.com/conda-forge/python-snappy-feedstock/pull/24

Sorry, I don't know why this slipped by.

**Comment by zaneselvans** [comment]
Great, thanks! Seems to have propagated and is working well in my environment now.
