### ISSUE TITLE
conda-forge packaging for linux-aarch64

### ISSUE THREAD

**Issue by ceejatec** [conda-forge/python-snappy-feedstock#30]
- [ x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

python-snappy isn't available for linux-aarch64. It seems like most conda-forge packages are available across all platforms; is there any chance this one will be added?

**Comment by martindurant** [comment]
You might want to try `cramjam` while someone figures out why this package isn't on aarch.

On September 16, 2021 10:02:08 PM EDT, Chris Hillery ***@***.***> wrote:
>
>
>- [ x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.
>
>Issue:
>
>python-snappy isn't available for linux-aarch64. It seems like most conda-forge packages are available across all platforms; is there any chance this one will be added?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/conda-forge/python-snappy-feedstock/issues/30
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ceejatec** [comment]
Appreciate the thought, but our use case is an existing series of programs written using snappy.

**Comment by jjacobelli** [comment]
https://github.com/conda-forge/python-snappy-feedstock/pull/31 should fix this

**Comment by martindurant** [comment]
Can we tell from the (successful) builds if aarch happened or not?

**Comment by jjacobelli** [comment]
> Can we tell from the (successful) builds if aarch happened or not?

We need to wait for this [CI](https://cloud.drone.io/conda-forge/python-snappy-feedstock/2) and the packages should be published

**Comment by jakirkham** [comment]
This was done  some time ago in PR: https://github.com/conda-forge/python-snappy-feedstock/pull/31
