### ISSUE TITLE
No python 3.6 version for linux (or windows)

### ISSUE THREAD

**Issue by martindurant** [conda-forge/python-snappy-feedstock#4]
I notice that a package was built for py36, osx in early January.
Can I please request a py36, linux64 package also?

**Comment by mariusvniekerk** [comment]
Submit a pr with the newest smithy rerender and it should pick it up.

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/conda-forge/python-snappy-feedstock/pull/5 ).
