### ISSUE TITLE
Package is `noarch: python` and is using compilers

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-snappy-feedstock#44]
In PR ( https://github.com/conda-forge/python-snappy-feedstock/pull/39 ), this package was converted to `noarch: python`

https://github.com/conda-forge/python-snappy-feedstock/blob/dbf939b834aa2c9ba19de892b4c94243bde6b91e/recipe/meta.yaml#L13-L16

However it still depends on compilers

https://github.com/conda-forge/python-snappy-feedstock/blob/dbf939b834aa2c9ba19de892b4c94243bde6b91e/recipe/meta.yaml#L18-L23

If this package is pure Python and OS independent, we can drop the `requirements/build` section

If the package still has Python or OS dependence, we may need to do something else

Please let me know which it is

**Comment by martindurant** [comment]
The compilers should be dropped, this is now truly noarch. I did that maybe in the PR that filed.

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
This should be fixed in PR: https://github.com/conda-forge/python-snappy-feedstock/pull/45
